# Machine-Specific Configuration
# This file is automatically generated during deployment
# Edit this to set machine-specific settings

{ config, pkgs, lib, ... }:

{
  # Machine hostname - set during deployment
  # Default hostname for this generated config; allow higher-priority overrides
  # from the flake entries (mkDefault avoids conflicts during flake checks).
  networking.hostName = lib.mkDefault "sifos-thin-client";
  
  # Tailscale IP for this machine (update after first tailscale up)
  # This helps document the Tailscale IP for remote RDP/SSH access
  sifos.tailscale.advertiseAddress = lib.mkDefault null;
  
  # Machine type selection is handled in flake outputs; keep this file for
  # per-machine knobs (hostname, tailscale, overrides). If using a non-flake
  # workflow, add your desired machine type module to `imports` below.
  imports = [ ];
  
  # Optional: Static IP configuration
  # Uncomment and configure if needed
  # networking.interfaces.enp1s0.ipv4.addresses = [{
  #   address = "192.168.0.100";
  #   prefixLength = 24;
  # }];
  # networking.defaultGateway = "192.168.0.1";
  # networking.nameservers = [ "8.8.8.8" "1.1.1.1" ];
  
  # Optional: Location/description (for documentation)
  # system.nixos.label = "Dispatch Station 1 - Main Office";
}
