# Machine-Specific Configuration
# This file is automatically generated during deployment
# Edit this to set machine-specific settings

{ config, pkgs, lib, ... }:

{
  # Machine hostname - set during deployment
  networking.hostName = "sifos-thin-client-1";
  
  # Machine type - determines which features are enabled
  # Options: thin-client, office, workstation, shop-kiosk, custom
  # Current: thin-client (set 2025-11-10)
  
  # Import machine type configuration
  imports = [
    ./machine-types/thin-client.nix
    # Change above line based on machine type:
    # ./machine-types/thin-client.nix
    # ./machine-types/office.nix
    # ./machine-types/workstation.nix
    # ./machine-types/shop-kiosk.nix
  ];
  
  # Optional: Static IP configuration
  # Uncomment and configure if needed
  # networking.interfaces.enp1s0.ipv4.addresses = [{
  #   address = "192.168.0.100";
  #   prefixLength = 24;
  # }];
  # networking.defaultGateway = "192.168.0.1";
  # networking.nameservers = [ "8.8.8.8" "1.1.1.1" ];
  
  # Optional: Location/description (for documentation)
  # system.nixos.label = "Dispatch Station 1 - Main Office";
}
