name: sif-os
description: "Custom uBlue image with Tailscale + Remmina out of the box"
base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  # Add Tailscale repo + install package
  - type: files
    files:
      - source: tailscale.repo
        destination: /etc/yum.repos.d/tailscale.repo

  - type: rpm-ostree
    install:
      - tailscale

  # Enable tailscaled service
  - type: systemd
    system:
      enabled:
        - tailscaled.service

  # Flatpaks (system-wide install)
  - type: flatpak
    system:
      install:
        - org.remmina.Remmina
    remotes:
      - remote: flathub
        url: https://dl.flathub.org/repo/flathub.flatpakrepo
